// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPGcB_psOuWxeHFEou5wtFp-Esy0jV15M',
    appId: '1:1063977302659:web:d7144f900a0925d617f9b6',
    messagingSenderId: '1063977302659',
    projectId: 'eyedrop-adherence-app',
    authDomain: 'eyedrop-adherence-app.firebaseapp.com',
    storageBucket: 'eyedrop-adherence-app.firebasestorage.app',
    measurementId: 'G-HMSNK3JVLE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmdsX41Q-2SvnuCw8yxmZehlV2IBRnFas',
    appId: '1:1063977302659:android:ebff254039dafe7817f9b6',
    messagingSenderId: '1063977302659',
    projectId: 'eyedrop-adherence-app',
    storageBucket: 'eyedrop-adherence-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHOMkyaA37_H2Y6GT4zuHnIc3Fg3JxwUk',
    appId: '1:1063977302659:ios:85a8f0a426cad80817f9b6',
    messagingSenderId: '1063977302659',
    projectId: 'eyedrop-adherence-app',
    storageBucket: 'eyedrop-adherence-app.firebasestorage.app',
    iosBundleId: 'com.example.eyedrop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHOMkyaA37_H2Y6GT4zuHnIc3Fg3JxwUk',
    appId: '1:1063977302659:ios:85a8f0a426cad80817f9b6',
    messagingSenderId: '1063977302659',
    projectId: 'eyedrop-adherence-app',
    storageBucket: 'eyedrop-adherence-app.firebasestorage.app',
    iosBundleId: 'com.example.eyedrop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPGcB_psOuWxeHFEou5wtFp-Esy0jV15M',
    appId: '1:1063977302659:web:5467e725160edb1a17f9b6',
    messagingSenderId: '1063977302659',
    projectId: 'eyedrop-adherence-app',
    authDomain: 'eyedrop-adherence-app.firebaseapp.com',
    storageBucket: 'eyedrop-adherence-app.firebasestorage.app',
    measurementId: 'G-EWSWGC8NKT',
  );
}
